language: node_js
node_js:
- 8.1.3
services:
  - postgresql
branches:
  only:
    - development
cache:
  directories:
   - "node_modules"
env:
  - TEST_DBURL=DATABASE_URL

script:
  - npm test


after_success:
  - npm run coverage